# This workflow will do a clean install of node dependencies, build the source code and run tests.
name: Smart-Gardening backend CI

on:
  pull_request:
    paths:
      - "backend/**"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing backend...
        run: npm install

      - name: Testing backend...
        run: npm test
