# This workflow will do a clean install of node dependencies, build the source code and run tests.
name: Smart-Gardening Fronted CI

on:
  pull_request:
    paths:
      - "frontend/**"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    defaults:
      run:
        working-directory: ./frontend

    env:
      REACT_APP_COGNITO_USER_POOL_ID: ${{ secrets.REACT_APP_COGNITO_USER_POOL_ID }}
      REACT_APP_COGNITO_CLIENT_ID: ${{ secrets.REACT_APP_COGNITO_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing frontend...
        run: npm install

      - name: Testing frontend...
        run: npm test
